inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'vcr_cassettes/**/*'
    - 'node_modules/**/*'
    - 'app/javascript/**/*'
    - 'db/**/*'
    - 'tmp/**/*'

