# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.6.0-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: myDB
      - image: redis:6.0-rc1-alpine3.11
    steps: 
      - checkout

      # - run: # Update bundler
      #     name: Bundle Install
      #     command: gem install bundler && bundle update --bundler

      - run: 
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - rails-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v1-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: rails-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle      

      - run:
          name: Create database
          command: bundle exec rake db:create

      # - run:
      #     name: Database setup
      #     command: bin/rails db:schema:load --trace

      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-

      - run:
          name: Yarn cache
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: Webpacker compile
          command: bundle exec rake webpacker:compile

      - save_cache:
         key: yarn-cache-v1-{{ checksum "yarn.lock" }}
         paths:
           - ~/.cache/yarn
            
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - run:
          name: Lint with rubocop
          command: bundle exec rubocop

      # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results

  deploy:
    docker: 
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master  

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
