twitter:
  every: 30s
  class: TweetSearchJob
  args: 10
  queue: twitter
  description: Runs the tweet search method

clean:
  every: 1h
  class: DeleteOldTweetsJob
  args: 
  queue: delete
  description: Hard delete old tweets