# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:helpers to regenerate.
module ApplicationHelper
  include Kernel
  include ActionView::Helpers
end

module HashtagsHelper
  include Kernel
  include ActionView::Helpers
end

module TweetsHelper
  include Kernel
  include ActionView::Helpers
end

module ActionController::Helpers
  sig { returns(T.all(ApplicationHelper, HashtagsHelper, TweetsHelper)) }
  def helpers; end
end
